version: 2
mergeable:

##############
### GLOBAL ###
##############
- when: pull_request.*, pull_request_review.*
  name: 'Naming convention'
  filter:
    - do: repository
      visibility: 'private'
      name:
        must_exclude:
          regex: '^(InSpark\.|Solution\.|BRC\.|DNA\.|DEV\.|SEC\.)'
  validate:
    - do: age
      created_at:
        days: 0
  fail:
    - do: checks 
      status: 'failure' 
      payload:
        title: 'Naming convention'
        summary: 'The repo is not following the naming convention'

#################
### SOLUTIONS ###
#################

- when: pull_request.*, pull_request_review.*
  name: 'Checking labels'
  filter:
    - do: repository
      visibility: 'private' # Can be public or private
      name:
        must_include:
          regex: 'Solution.*'
  validate:
    - do: label
      must_include:
        regex: 'patch|minor|major|no-release'
        regex_flag: 'none'
        message: 'Must have a version increment label'
  fail:
    - do: checks 
      status: 'failure' 
      payload:
        title: 'Must have a version increment or no-release label'
        summary: "All the validators have returned 'pass'! \n Here are some stats of the run: \n {{validationCount}} validations were ran"

- when: schedule.repository
  filter:
    - do: repository
      visibility: 'public' # Can be public or private
      name:
        must_include:
          regex: 'Solution.*'
  validate:
    - do: stale
      days: 30
      type: pull_request
      ignore_drafts: true
      ignore_milestones: true
      ignore_projects: true
      time_constraint:
        time_zone: 'Europe/Amsterdam'
        hours_between: ['9', '17']
        days_of_week: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri']
  pass:
    - do: comment
      payload:
        body: This PR is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 10 days.
    - do: labels
      add: 'Stale'