name: markdown check compliance 

on:
  repository_dispatch:
    types: [org-workflow-bot]  
   
jobs:
  register:
    runs-on: ubuntu-latest
    steps:
    - uses: SvanBoxel/organization-workflow@main
      with:
        id: ${{ github.event.client_payload.id }}
        callback_url: ${{ github.event.client_payload.callback_url }}
        sha: ${{ github.event.client_payload.sha }}
        run_id: ${{ github.run_id }}
        name: ${{ env.name || github.workflow }}
        documentation: ".github/workflows/github-check.md"
        enforce: true
        enforce_admin: true
        
  main:
    needs: [register]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
#     # Analyze Azure resources using PSRule for Azure
#     - name: Analyze Azure template files
#       uses: microsoft/ps-rule@v2.2.0
#       with:
#         modules: 'PSRule.Rules.GitHub'
        
    - name: PowerShell script
      # You may pin to the exact commit or the version.
      # uses: Amadevus/pwsh-script@1f1751bbf3d1a92127bfc6c32403283625880cbf
      uses: Amadevus/pwsh-script@v2.0.1
      with:
        # PowerShell script to execute in Actions-hydrated context
        script: |
          Install-Module -Name 'PSRule.Rules.GitHub' -Scope CurrentUser;
          Export-GitHubRuleData -Repository ${{ github.repository }};
          Assert-PSRule -Module 'PSRule.Rules.GitHub' -InputPath .\*.json -Format Json;
          
